import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/component/shared/Sidebar";
import Navbar from "@/component/shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create dashboard",
  description: "Generated by create dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    <div className="min-h-screen ">
      <div className="flex justify-between ">
        <div className=" bg-[#111B3C] w-[16%] border-r-[1px] border-white">
          <Sidebar />
        </div>
        <div className="w-[84%]   ">
            <Navbar></Navbar>
          {children}</div>
      </div>
    </div>
      </body>
    </html>
  );
}
